### ISSUE TITLE
status of this fork

### ISSUE THREAD

**Issue by NanneHuiges** [stiftungswo/Dime#1]
Hey, opening this as an 'issue' because that seems the best way to conctact: just a quick question or two

This fork looks like it has more active development then the one from @phpugl , so it looks like a good choice: but what is the status of this branch? Is it useable and/or "production" (lets call it beta) ready?

There's 2 commits in phpugl/Dime that arent merged, are they to far apart , or is that just a 'todo'?

**Comment by Toasterson** [comment]
Hi

It was originally a fork from the phpugl one but has since then strayed from their idea.
They wanted a string parser kind of application, this is a complete REST based Object Database with a WebGui. Mobile Support either via App or Responsive design is also planned.
Commits from PHPugl will thus not be merged.

It has and will be more actively developed, as we use this application for our own Contract Management.
It's basicly openERP but with a more KISS aproach for the Datamodel. (and less Modules)

The Backend is production ready. It does its job reliable and only gets some changes when there are new Entities added. Although I'm thinking of rewriting the REST Handler Class to Fire Events and to merge the Controllers. The GUI unfortunatly suffers from a bit rot. The Javascript Framework i used was not up to the task. Im Rewriting it in Angular Dart. (Same as AngularJS but with a Language i am able to wrap my head around)

**Comment by NanneHuiges** [comment]
Thanks for the answer!
Sounds good! I was looking at projects to use for simple time-tracking, not full ERP per se, but a more rich/developed project is always a pro.

I'll switch over to this fork. Did you ever build a Dockerfile for this maybe? I was collection some information for it for the phpugl repo, but I guess it's not that different for this fork?

**Comment by Toasterson** [comment]
I dont use docker. I find its deployment process to be ok for releases but not for development. I have however a Vagrantfile and pupet scripts in the env folder. PHPUGL does AFAIK not have anything in the sense of automated installation scripts. 

If you want to deploy it or make a dockerfile, have a look at the shell scripts in the env/shell folder. They do all the work when setting up a dev environment in a vagrant VM.
The only thing they don't do is a Git submodule update to pull the other bundles that are not in vendor.

**Comment by NanneHuiges** [comment]
awesome!
